### ISSUE TITLE
nuget log4net version dependency

### ISSUE THREAD

**Issue by DarthChucks** [DavidChristiansen/DNOA4Glimpse#1]
NuGet automatically installs log4net 1.2.11 when installing DNOA4Glimpse.  It then gives the following error:

Could not load file or assembly 'log4net, Version=1.2.10.0, Culture=neutral, PublicKeyToken=1b44e1d426115821' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Attempted to correct this by adding the following to the web.config:
&lt;dependentAssembly&gt;
    &lt;assemblyIdentity name="log4net" publicKeyToken="1b44e1d426115821" culture="neutral" /&gt;
    &lt;bindingRedirect oldVersion="0.0.0.0-1.2.11.0" newVersion="1.2.11.0" /&gt;
&lt;/dependentAssembly&gt;

Now I get the error:

Could not load file or assembly 'log4net, Version=1.2.11.0, Culture=neutral, PublicKeyToken=1b44e1d426115821' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by DavidChristiansen** [comment]
Hi there,
Thanks for the report. Whist I investigate what is pulling down the new log4net, you should download the version of log4net signed with the old key. For specific information please review my posting on stackoverflow: 

http://stackoverflow.com/questions/8743992/how-do-i-work-around-log4net-keeping-changing-publickeytoken/8806628#8806628

They really have screwed up alot of things with the new version of log4net but hopefully we can get to the bottom of whats going on a provide a long term fix.

**Comment by DarthChucks** [comment]
David,
    Thanks for the quick response.  I see that this is not a DNOA4Glimpse issue, but a log4net issue.
